blank_issues_enabled: false
contact_links:
  - name: Kiccha Request Support group
    url: https://t.me/KicchaRequest
    about: Please drop your doubts or queries there for an immediate response.
  - name: Movie Update Channel
    url: https://t.me/GD_FILMCLUB
    about: Basic documentation for setting up.
